### ISSUE TITLE
RE2 not showing in vr headset

### ISSUE THREAD

**Issue by mattex40** [praydog/REFramework#118]
i have a CV1, and the game not showing in VR, only on monito
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7799513/re2_framework_log.txt)
r

**Comment by teddybear082** [comment]
Noob here but I see a lot of DirectX12 mentions on your log, did you change to DX11 in the files?  Only DX11 works if I recall correctly.

**Comment by praydog** [comment]
Fixed in https://github.com/praydog/REFramework/commit/163704a8521e01916abfd78ae863a46135c7228d for D3D12. Improvements will come later. Colors will still be washed out or incorrect in HDR but there will at least be video output. It will still be playable with HDR on if you can tolerate not having correct colors. HDR should still be turned off as as complete fix.

New builds can be found here: https://github.com/praydog/REFramework-nightly/releases/
