### ISSUE TITLE
RE7

### ISSUE THREAD

**Issue by Marirarius89** [praydog/REFramework#452]
I am unable to start the game in my headset. It displays in VR, but then just loads forever. I am using a Quest 2 via Link cable. RTX 3070 Ti, Windows 11. Anyone able to help me?

**Comment by d0x360** [comment]
Have you tried using virtual desktop on the quest and the virtual desktop client on the PC?  That seems to be the most performante way to run quest on PC from my experience and also tends to solve things like this although I may be wrong since every project is different.  

It essentially allows you to bypass the oculus runtime which transcodes the GPU output into a video.  Virtual desktop also sends you a video but it doesn't have as many issues when it comes to a game running on steam vr.
