### ISSUE TITLE
Natives

### ISSUE THREAD

**Issue by Kobi-Blade** [praydog/REFramework#836]
**Is your feature request related to a problem? Please describe.**
We shouldn't rely on third-parties like Fluffy Manager, support can be dropped any time and people don't like to have 2 to 3 different tools to MOD one game.

As for being related to a problem, we been unable to MOD MHR ever since Update 16, due to lack of updates on Fluffy Manager.

This wouldn't be a problem if we were relying solely on REFramework.

**Describe the solution you'd like**
Native support to load loose files, it will simplify modding.

**Describe alternatives you've considered**
For MHR there's already a [library](https://www.nexusmods.com/monsterhunterrise/mods/848) that gives us this feature, however is outdated and buggy.

**Additional context**
This should be one of the basic REFramework features, since is the go to tool to mod CAPCOM games.

**Comment by praydog** [comment]
While this would certainly be a nice feature, are you sure these mods you're referring to are broken? The mods that they're loading can cause infinite loading and other issues due to CRC mismatches in the new game data and whatnot.

I'll consider it though, games other than MHRise are missing something like FirstNatives to facilitate fast mod development.

**Comment by praydog** [comment]
Added a month or so ago with the "LooseFileLoader" option.
