### ISSUE TITLE
RE 3 running at 9 FPS after most recent Steam 2.# VR update

### ISSUE THREAD

**Issue by eeeeyuke** [praydog/REFramework#937]
**Describe the bug**
A clear and concise description of what the bug is. If the bug only started to happen after a certain REFramework update, let us know which version the bug appeared in.

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as well.

**Identify the REFramework version**
If the REFramework version or commit hash is known, submit this information.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop and VR (please complete the following information):**
 - Windows 11
 - 4070
 - 7800x3D

**Steam Deck/Linux (please complete the following information):**
 - Proton version

**Virtual Reality (please complete the following information):**
 - Headset model
![41a6ff694887a9595f2bb9b45d4664a5](https://github.com/praydog/REFramework/assets/148450234/503a7a63-8c94-4320-b5a0-c6a59b3ff387)

 - Runtime (OpenVR or OpenXR)

**Additional context**

**Comment by ArcadaLabs-Jason** [comment]
+1

**Comment by MagellanOo** [comment]
Following this Steam post: https://steamcommunity.com/app/250820/discussions/0/4036976070310250790/
I removed the whole game, the graphics should get reset by this. I switched to Steam Beta and SteamVR Beta. The game runs smooth on my side. 

Don't forget to rename the two executable under those folders -> C:\Program Files (x86)\Steam\steamapps\common\SteamVR\tools\steamvr_desktop_game_theater to block Steam Theater to lunch.

**Comment by eeeeyuke** [comment]
The steam theater issue was resolved.  Now, as far as removing the whole game...I'm assuming there are steps beyond a simple uninstall via steam.  If it's not a hassle, what would that encompass?  I've also gone back to Steam VR beta, but didn't do that with just Steam.  Will try when I get home, but in the meantime, any help with a COMPLETE removal of RE3 from my PC would be appreciated.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MagellanOo** [comment]
Just remove the game via Steam and afterwards the folder if it still there.
What I also realized when starting the RE game, get your controllers ready, tracked and stay in your VR environment/play area without any VR overlay active and wait for the game to lunch.

**Comment by eeeeyuke** [comment]
THIS WORKED!  Steam VR Beta, Steam Beta, and launch in Steam VR with no overlay and controllers tracked.  Thank you SO MUCH!

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Spigarg** [comment]
I have this same problem. I have never tried this VR mod before so I have no prior experience of this mod working as it should with my system. Tried all these fixes:
-reinstall game and remove the whole folder
-tried two different and recommended older nvidia drivers
-steambeta, steamvr beta

log uploaded:
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/13467566/re2_framework_log.txt)

Identify the REFramework version
-the current one

Desktop and VR (please complete the following information):

Windows 11
4090
13900k intel
Steamvr

Headset: Varjo aero, which means I always have to use varjo base software, which opens steamvr for me. I have tried the lowest settings possible and my fps doesnt change (around 10-20 or possibly even a crash). The menu is low fps and the gameplay is low fps no matter what settings I put in game or thru varjo.

Hope to get this fixed because the mod looks amazing.

**Comment by Spigarg** [comment]
> Hello @Spigarg,
> 
> Have you tired launching the game through the headset with Steam VR Beta, and after clicking on lunch, to immediately close all VR overlays and having the controllers tracked?

Not sure what you mean by VR overlays. Ive tried steamvr beta and launch the game while wearing glasses and using my controllers to open the game through steamvr. It doesnt let me open through steamvrhome since RES2 isnt a true vr game so it doesnt give me it as an option. I also cant shut down varjo base since steamvr wont work without it when using varjo glasses.
